# Generated by Django 5.1.4 on 2025-04-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
